version: "3.8"

services:
  microhub:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379?password=sOmE_sEcUrE_pAsS
      - REDIS_PASSWORD=sOmE_sEcUrE_pAsS
      - APP_PORT=3000
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=microhub
    ports:
      - 3000:3000

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
    # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: microhub
    volumes:
      - ./docker/mysql/seed.sql:/docker-entrypoint-initdb.d/database.sql
      - ./docker/mysql/extra.cnf:/etc/mysql/conf.d/extra.cnf
